HashScout: com.github.mgrl39.hashscout.FileOrganizer Class Reference
com.github.mgrl39.hashscout.FileOrganizer Class Reference
Organitzador de fitxers que demostra l'ús avançat de característiques Java modernes.
Public Member Functions
FileOrganizer (Logger logger)
Constructor que injecta dependències.
void organizeFiles (Path folder, Consumer< Double > progressConsumer)
Organitza els fitxers d'una carpeta en categories.
Private Member Functions
String getExtension (String fileName)
Obté l'extensió d'un fitxer.
String getCategoryForExtension (String extension)
Classifica els fitxers per extensió
Private Attributes
final Logger logger
Logger per registrar events i errors.
Detailed Description
Organitzador de fitxers que demostra l'ús avançat de característiques Java modernes.
Aquesta classe exemplifica:
Ús de Streams per processar fitxers de manera eficient
Expressions regulars per classificar extensions
Lambdes per operacions funcionals
Gestió d'excepcions amb try-catch
Programació concurrent amb threads
Patró Observer amb Consumer<Double>
Author
mgrl39
Definition at line 26 of file FileOrganizer.java.
Constructor & Destructor Documentation
FileOrganizer()
com.github.mgrl39.hashscout.FileOrganizer.FileOrganizer (Logger logger) inline
Constructor que injecta dependències.
Parameters
logger Sistema de logging per registrar missatges
Definition at line 36 of file FileOrganizer.java.
{
        this.logger = logger;
    }
References com.github.mgrl39.hashscout.FileOrganizer.logger.
Member Function Documentation
getCategoryForExtension()
String com.github.mgrl39.hashscout.FileOrganizer.getCategoryForExtension (String extension) inline private
Classifica els fitxers per extensió
Demostra l'ús efectiu d'expressions regulars per categoritzar fitxers de manera flexible i mantenible
Parameters
extension Extensió del fitxer a classificar
Returns
String amb la categoria corresponent
Expressions regulars per match d'extensió (pattern matching)
Definition at line 132 of file FileOrganizer.java.
{
        if (extension.matches("zip|rar|7z|tar|gz|bz2")) return "comprimits";
        if (extension.matches("jpg|jpeg|png|gif|bmp|webp|svg")) return "imatges";
        if (extension.matches("mp3|wav|ogg|m4a|flac")) return "audio";
        if (extension.matches("mp4|avi|mkv|mov|wmv")) return "video";
        if (extension.matches("doc|docx|pdf|txt|rtf|odt")) return "documents";
        if (extension.matches("exe|msi|deb|rpm|appimage")) return "executables";
        if (extension.matches("js|ts|java|py|cpp|cs|php|html|css")) return "codi";
        if (extension.matches("json|xml|yaml|yml|ini|conf")) return "config";
        return "others";  // Categoria per defecte
    }
getExtension()
String com.github.mgrl39.hashscout.FileOrganizer.getExtension (String fileName) inline private
Obté l'extensió d'un fitxer.
Utilitza String.lastIndexOf de manera eficient amb operador ternari per gestionar casos sense extensió
Parameters
fileName Nom del fitxer a analitzar
Returns
String amb l'extensió o "No_Extension" si no en té
Busca l'última ocurrència del punt
Operador ternari per gestionar casos sense extensió
Definition at line 116 of file FileOrganizer.java.
{
        int lastIndex = fileName.lastIndexOf(".");
        return lastIndex == -1 ? "No_Extension" : fileName.substring(lastIndex + 1);
    }
organizeFiles()
void com.github.mgrl39.hashscout.FileOrganizer.organizeFiles (Path folder, Consumer< Double > progressConsumer) inline
Organitza els fitxers d'una carpeta en categories.
Demostra:
Ús de try-with-resources amb Streams (tanca recursos automàticament)
Lambdes amb files.forEach (processament funcional)
HashMap per comptabilitzar categories (estructura de dades)
Gestió concurrent amb AtomicBoolean (sincronització segura)
Expressions regulars per classificar fitxers (pattern matching)
Parameters
folder Carpeta a organitzar
progressConsumer Consumer per actualitzar el progrés (patró Observer)
Flag atòmic per indicar finalització als threads
Thread per simular progrés de manera visual
Thread principal per organitzar fitxers de manera asíncrona
try-with-resources garanteix tancament correcte de l'Stream
Mapa per comptabilitzar fitxers per categoria
Processa cada fitxer amb lambdes (programació funcional)
Obté l'extensió i determina la categoria
Crea directoris si no existeixen
Mou el fitxer a la categoria corresponent
Incrementa comptador de categoria (merge és thread-safe)
Gestió d'excepcions específica
Registra finalització i estadístiques
Utilitza lambdes per iterar el mapa i mostrar resultats
Gestió d'excepcions global del procés
Assegura que el flag de finalització es marca
Definition at line 53 of file FileOrganizer.java.
{
        AtomicBoolean completed = new AtomicBoolean(false);
        Thread progressThread = new Thread(() -> ProgressUtils.simulateProgress(progressConsumer, completed));
        progressThread.setDaemon(true);  // Thread daemon (no bloqueja tancament de l'aplicació)
        progressThread.start();
        new Thread(() -> {
            try (Stream<Path> files = Files.list(folder)) {  // Llista tots els fitxers de la carpeta
                Map<String, Integer> categoryCount = new HashMap<>();
                files.forEach(file -> {
                    if (Files.isRegularFile(file)) {  // Comprova que sigui un fitxer regular
                        try {
                            String extension = getExtension(file.getFileName().toString());
                            String category = getCategoryForExtension(extension);
                            Path targetDir = folder.resolve(category);  // Crea la ruta destí
                            Files.createDirectories(targetDir);
                            Files.move(file, targetDir.resolve(file.getFileName()));
                            categoryCount.merge(category, 1, Integer::sum);
                        } catch (IOException e) {
                            logger.log("❌ Error movent fitxer: " + e.getMessage());
                        }
                    }
                });
                logger.log("✔️ Organització completa");
                categoryCount.forEach((category, count) ->
                        logger.log("   " + category + ": " + count + " fitxers"));
            } catch (IOException e) {
                logger.log("❌ Error organitzant: " + e.getMessage());
            } finally {
                completed.set(true);
            }
        }).start();  // Inicia el thread d'organització
    }
References com.github.mgrl39.hashscout.Logger.log(), com.github.mgrl39.hashscout.FileOrganizer.logger, and com.github.mgrl39.hashscout.ProgressUtils.simulateProgress().
Referenced by com.github.mgrl39.hashscout.MainController.onOrganizeFiles().
Member Data Documentation
logger
final Logger com.github.mgrl39.hashscout.FileOrganizer.logger private
Logger per registrar events i errors.
Definition at line 29 of file FileOrganizer.java.
Referenced by com.github.mgrl39.hashscout.FileOrganizer.FileOrganizer(), and com.github.mgrl39.hashscout.FileOrganizer.organizeFiles().
The documentation for this class was generated from the following file:
src/main/java/com/github/mgrl39/hashscout/FileOrganizer.java