HashScout: com.github.mgrl39.hashscout.ProgressUtils Class Reference
com.github.mgrl39.hashscout.ProgressUtils Class Reference
Utilitat per simular i gestionar barres de progrés de manera concurrent.
Static Public Member Functions
static void simulateProgress (Consumer< Double > progressConsumer, AtomicBoolean completed)
Simula el progrés d'una operació de manera suau.
Detailed Description
Utilitat per simular i gestionar barres de progrés de manera concurrent.
Aquesta classe demostra:
Ús de AtomicBoolean per sincronització
Lambdes amb Consumer
Platform.runLater per UI thread-safe
Gestió de threads daemon
Author
mgrl39
Definition at line 20 of file ProgressUtils.java.
Member Function Documentation
simulateProgress()
static void com.github.mgrl39.hashscout.ProgressUtils.simulateProgress (Consumer< Double > progressConsumer, AtomicBoolean completed) inline static
Simula el progrés d'una operació de manera suau.
Implementa:
Control concurrent amb AtomicBoolean
Actualitzacions UI thread-safe
Gestió d'interrupcions
Increment gradual del progrés
Parameters
progressConsumer Consumer per actualitzar la UI
completed Flag de finalització
Definition at line 34 of file ProgressUtils.java.
{
        try {
            double progress = 0;
            while (!completed.get() && progress < 1.0) {
                progress += 0.05;
                final double currentProgress = progress;
                Platform.runLater(() -> progressConsumer.accept(currentProgress));
                Thread.sleep(100);
            }
            Platform.runLater(() -> progressConsumer.accept(1.0));
        } catch (InterruptedException ignored) {}
    }
Referenced by com.github.mgrl39.hashscout.HashGenerator.generateHashWithProgress(), com.github.mgrl39.hashscout.FileOrganizer.organizeFiles(), and com.github.mgrl39.hashscout.FileSearcher.searchText().
The documentation for this class was generated from the following file:
src/main/java/com/github/mgrl39/hashscout/ProgressUtils.java