HashScout: com.github.mgrl39.hashscout.Logger Class Reference
com.github.mgrl39.hashscout.Logger Class Reference
Sistema de logging que implementa registre concurrent i formatat.
Public Member Functions
Logger (TextArea logTerminal)
void log (String message)
Registra un missatge amb timestamp al terminal.
Private Attributes
final TextArea logTerminal
Detailed Description
Sistema de logging que implementa registre concurrent i formatat.
Aquesta classe demostra:
Ús de DateTimeFormatter per timestamps
Actualitzacions UI thread-safe
Gestió eficient de TextArea
Format consistent de missatges
Author
mgrl39
Definition at line 21 of file Logger.java.
Constructor & Destructor Documentation
Logger()
com.github.mgrl39.hashscout.Logger.Logger (TextArea logTerminal) inline
Definition at line 25 of file Logger.java.
{
        this.logTerminal = logTerminal;
    }
References com.github.mgrl39.hashscout.Logger.logTerminal.
Member Function Documentation
log()
void com.github.mgrl39.hashscout.Logger.log (String message) inline
Registra un missatge amb timestamp al terminal.
Implementa:
Format consistent de data/hora
Platform.runLater per thread safety
Auto-scroll del terminal
Format visual amb emojis
Parameters
message Missatge a registrar
Definition at line 40 of file Logger.java.
{
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        Platform.runLater(() -> {
            logTerminal.appendText(String.format("[%s] %s%n", timestamp, message));
            logTerminal.setScrollTop(Double.MAX_VALUE);
        });
    }
References com.github.mgrl39.hashscout.Logger.logTerminal.
Referenced by com.github.mgrl39.hashscout.MainController.initialize(), com.github.mgrl39.hashscout.MainController.onGenerateHash(), com.github.mgrl39.hashscout.MainController.onOrganizeFiles(), com.github.mgrl39.hashscout.MainController.onSelectFile(), com.github.mgrl39.hashscout.MainController.onSelectFolderForOrganization(), com.github.mgrl39.hashscout.MainController.onSelectFolderForSearch(), com.github.mgrl39.hashscout.FileOrganizer.organizeFiles(), and com.github.mgrl39.hashscout.FileSearcher.searchText().
Member Data Documentation
logTerminal
final TextArea com.github.mgrl39.hashscout.Logger.logTerminal private
Definition at line 23 of file Logger.java.
Referenced by com.github.mgrl39.hashscout.Logger.log(), and com.github.mgrl39.hashscout.Logger.Logger().
The documentation for this class was generated from the following file:
src/main/java/com/github/mgrl39/hashscout/Logger.java