HashScout: com.github.mgrl39.hashscout.HashGenerator Class Reference
com.github.mgrl39.hashscout.HashGenerator Class Reference
Generador de hashes que implementa múltiples algorismes de manera segura i eficient.
Public Member Functions
String generateHash (File file, String algorithm) throws Exception
Genera el hash d'un fitxer utilitzant l'algorisme especificat.
void generateHashWithProgress (File file, String algorithm, Consumer< String > resultConsumer, Consumer< Double > progressConsumer)
Genera hash de manera asíncrona amb indicador de progrés.
Detailed Description
Generador de hashes que implementa múltiples algorismes de manera segura i eficient.
Aquesta classe demostra:
Ús de MessageDigest per generació segura de hashes
Programació concurrent amb threads
Gestió d'excepcions robusta
Patró Observer per actualitzacions de progrés
Interfície fluida amb Consumers
Author
mgrl39
Definition at line 25 of file HashGenerator.java.
Member Function Documentation
generateHash()
String com.github.mgrl39.hashscout.HashGenerator.generateHash (File file, String algorithm) throws Exception inline
Genera el hash d'un fitxer utilitzant l'algorisme especificat.
Demostra:
Ús segur de MessageDigest
Gestió eficient de fitxers amb Files
Conversió hexadecimal optimitzada
Parameters
file Fitxer a processar
algorithm Algorisme de hash (MD5, SHA-1, SHA-256)
Returns
String Hash en format hexadecimal
Exceptions
Exception Si hi ha errors en la lectura o el hash
Definition at line 40 of file HashGenerator.java.
{
        MessageDigest digest = MessageDigest.getInstance(algorithm);
        byte[] bytes = Files.readAllBytes(file.toPath());
        byte[] hash = digest.digest(bytes);
        return HexFormat.of().formatHex(hash);
    }
Referenced by com.github.mgrl39.hashscout.HashGenerator.generateHashWithProgress().
generateHashWithProgress()
void com.github.mgrl39.hashscout.HashGenerator.generateHashWithProgress (File file, String algorithm, Consumer< String > resultConsumer, Consumer< Double > progressConsumer) inline
Genera hash de manera asíncrona amb indicador de progrés.
Implementa:
Threads per operacions asíncrones
Lambdes per callbacks
Platform.runLater per actualitzacions UI
Gestió d'errors amb try-catch
Parameters
file Fitxer a processar
algorithm Algorisme seleccionat
resultConsumer Consumer pel resultat
progressConsumer Consumer pel progrés
Definition at line 61 of file HashGenerator.java.
{
        AtomicBoolean completed = new AtomicBoolean(false);
        Thread progressThread = new Thread(() -> ProgressUtils.simulateProgress(progressConsumer, completed));
        progressThread.setDaemon(true);
        progressThread.start();
        new Thread(() -> {
            try {
                String hash = generateHash(file, algorithm);
                final String result = algorithm + ": " + hash;
                Platform.runLater(() -> resultConsumer.accept(result));
            } catch (Exception e) {
                Platform.runLater(() -> resultConsumer.accept("Error: " + e.getMessage()));
            } finally {
                completed.set(true);
            }
        }).start();
    }
References com.github.mgrl39.hashscout.HashGenerator.generateHash(), and com.github.mgrl39.hashscout.ProgressUtils.simulateProgress().
Referenced by com.github.mgrl39.hashscout.MainController.onGenerateHash().
The documentation for this class was generated from the following file:
src/main/java/com/github/mgrl39/hashscout/HashGenerator.java