HashScout: com.github.mgrl39.hashscout.FileSearcher Class Reference
com.github.mgrl39.hashscout.FileSearcher Class Reference
Cercador de text que implementa cerca concurrent i eficient.
Public Member Functions
FileSearcher (Logger logger)
void searchText (Path folder, String searchTerm, Consumer< String > resultConsumer, Consumer< Double > progressConsumer)
Cerca text en fitxers de manera concurrent.
Private Attributes
final Logger logger
Detailed Description
Cercador de text que implementa cerca concurrent i eficient.
Demostra:
Ús avançat de Streams amb Files.walk
Programació concurrent segura
Gestió eficient de recursos
Patró Observer per resultats
StringBuilder per rendiment
Definition at line 25 of file FileSearcher.java.
Constructor & Destructor Documentation
FileSearcher()
com.github.mgrl39.hashscout.FileSearcher.FileSearcher (Logger logger) inline
Definition at line 29 of file FileSearcher.java.
{
        this.logger = logger;
    }
References com.github.mgrl39.hashscout.FileSearcher.logger.
Member Function Documentation
searchText()
void com.github.mgrl39.hashscout.FileSearcher.searchText (Path folder, String searchTerm, Consumer< String > resultConsumer, Consumer< Double > progressConsumer) inline
Cerca text en fitxers de manera concurrent.
Implementa:
Streams per recórrer fitxers
Lambdes per processar resultats
Platform.runLater per actualitzacions UI
Try-with-resources per gestió de recursos
Parameters
folder Carpeta on cercar
searchTerm Text a cercar
resultConsumer Consumer pels resultats
progressConsumer Consumer pel progrés
Definition at line 47 of file FileSearcher.java.
{
        AtomicBoolean searchCompleted = new AtomicBoolean(false);
        Thread progressThread = new Thread(() -> ProgressUtils.simulateProgress(progressConsumer, searchCompleted));
        progressThread.setDaemon(true);
        progressThread.start();
        new Thread(() -> {
            try (Stream<Path> files = Files.walk(folder).filter(Files::isRegularFile).limit(100)) {
                List<Path> fileList = files.collect(Collectors.toList());
                int matchingFiles = 0;
                for (Path file : fileList) {
                    List<String> lines = Files.readAllLines(file);
                    StringBuilder fileResults = new StringBuilder();
                    boolean foundMatch = false;
                    for (int i = 0; i < lines.size(); i++) {
                        if (lines.get(i).contains(searchTerm)) {
                            if (!foundMatch) {
                                fileResults.append("\n📄 ").append(file.getFileName()).append(":\n");
                                foundMatch = true;
                            }
                            fileResults.append("   Línia ").append(i + 1).append(": ")
                                       .append(lines.get(i).trim()).append("\n");
                        }
                    }
                    if (foundMatch) {
                        matchingFiles++;
                        final String results = fileResults.toString();
                        Platform.runLater(() -> resultConsumer.accept(results));
                    }
                }
                logger.log("🔎 Cerca completa: " + matchingFiles + " coincidències trobades");
            } catch (IOException e) {
                logger.log("❌ Error durant la cerca: " + e.getMessage());
            } finally {
                searchCompleted.set(true);
            }
        }).start();
    }
References com.github.mgrl39.hashscout.Logger.log(), com.github.mgrl39.hashscout.FileSearcher.logger, and com.github.mgrl39.hashscout.ProgressUtils.simulateProgress().
Referenced by com.github.mgrl39.hashscout.MainController.onSearchText().
Member Data Documentation
logger
final Logger com.github.mgrl39.hashscout.FileSearcher.logger private
Definition at line 27 of file FileSearcher.java.
Referenced by com.github.mgrl39.hashscout.FileSearcher.FileSearcher(), and com.github.mgrl39.hashscout.FileSearcher.searchText().
The documentation for this class was generated from the following file:
src/main/java/com/github/mgrl39/hashscout/FileSearcher.java